name: Build jServ Release

on: [push]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Show directory
        run: ls
      - name: Get Dart
        run: |
          sudo apt update
          sudo apt install apt-transport-https -y
          sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt update
          sudo apt install dart -y
      - name: Build
        run: cd Server && pub get && PATH=$PATH:/usr/lib/dart/bin dart compile exe main.dart -o jserv
      - name: Make tarball
        run: |
          mkdir release
          mv Server/jserv release/.
          cp -rv Server/Databases release/.
          cp Server/config.json release/.
          cp Server/*.jserv release/.
          tar -czvf jserv.tar.gz Server/release
          rm -rf Server/release
      - name: Push tarball as artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: jserv.tar.gz
          retention-days: 5